# FunASR Streaming ASR Engine Configuration
# 引擎名称
NAME: FunasrStreamingASR
# FunASR Onnx模型目录 (请根据实际情况修改或确保可通过snapshot_download获取)
MODEL_DIR: iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx
# Paraformer chunk_size 设置，影响流式识别的延迟和计算量
# [encode_chunk_size, decode_chunk_size, decode_left_chunk_size]
# e.g. [5, 10, 5] or [8, 8, 4] from example
CHUNK_SIZE: [8, 8, 4]
# 模型相关参数 (根据 funasr_onnx.paraformer_online_bin.Paraformer 初始化参数设定)
# BATCH_SIZE: 目前仅支持1
BATCH_SIZE: 1
# QUANTIZE: 是否使用量化模型
QUANTIZE: True
# INTRA_OP_NUM_THREADS: ONNX intra_op_num_threads
INTRA_OP_NUM_THREADS: 4

# 定义哪些参数可以通过config传递给引擎构造函数
PARAMETERS: ["MODEL_DIR", "CHUNK_SIZE", "BATCH_SIZE", "QUANTIZE", "INTRA_OP_NUM_THREADS"]
